version: '3.5'

services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    networks:
      - springboot-react-keycloak-net

  mongodb:
    image: mongo:7.0.12
    ports:
      - "27017:27017"
    networks:
      - springboot-react-keycloak-net

  keycloak:
    image:  quay.io/keycloak/keycloak:25.0.2
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

    networks:
      - springboot-react-keycloak-net




networks:
  springboot-react-keycloak-net: